// Generated by RUN-TRAINER-OWN-ALLOCATIONS-V5.3.6.ps1.
export const TRAINER_ALLOCATION_TABLE =
  'teaching_allocations' as const;

export const TRAINER_ALLOCATION_OWNER_COLUMN =
  'trainer_id' as const;

export const TRAINER_TABLE =
  'trainers' as const;
