// Generated by RUN-TRAINER-MISSING-DOCUMENTS-V5.3.ps1.
// The runner discovers the allocation table already used by the staff unit routes.
export const TRAINER_ALLOCATION_TABLE = 'teaching_allocations' as const;
