/**
 * SHARED UNIT ALIAS MAP (CND <-> DND Harmonization)
 * Maps normalized unit codes and titles to canonical curriculum keys across all 3 modules.
 */

export const SHARED_UNIT_ALIAS_MAP: Record<string, string> = {
  "informationcommunicationtechnology": "information_communication_technology",
  "cnd1201": "information_communication_technology",
  "dnd1201": "information_communication_technology",
  "ccu1102": "information_communication_technology",
  "dcu1102": "information_communication_technology",
  "dhn1102": "information_communication_technology",
  "cnd102": "information_communication_technology",
  "dnd102": "information_communication_technology",
  "cnd101": "communication_skills",
  "ict": "information_communication_technology",
  "310": "information_communication_technology",
  "entrepreneurship": "entrepreneurship",
  "cnd1306": "entrepreneurship",
  "dnd1306": "entrepreneurship",
  "ccu1105": "entrepreneurship",
  "dcu1105": "entrepreneurship",
  "dhn1103": "entrepreneurship",
  "cnd103": "entrepreneurship",
  "dnd103": "entrepreneurship",
  "entrepreneurshipeducation": "entrepreneurship",
  "410": "entrepreneurship",
  "communicationskills": "communication_skills",
  "cnd1101": "communication_skills",
  "dnd105": "communication_skills",
  "dnd1101": "communication_skills",
  "ccu1101": "communication_skills",
  "dcu1101": "communication_skills",
  "dhn1101": "communication_skills",
  "510": "communication_skills",
  "lifeskills": "life_skills",
  "cnd1103": "life_skills",
  "dnd1103": "life_skills",
  "ccu1106": "life_skills",
  "dcu1106": "life_skills",
  "dhn1104": "life_skills",
  "cnd104": "life_skills",
  "dnd104": "life_skills",
  "610": "life_skills",
  "basicmathematics": "basic_mathematics",
  "cnd1104": "basic_mathematics",
  "dnd1104": "basic_mathematics",
  "ccu1110": "basic_mathematics",
  "dcu1110": "basic_mathematics",
  "dhn1105": "human_anatomy_and_physiology",
  "mathematics": "basic_mathematics",
  "710": "basic_mathematics",
  "physicalscience": "physical_science",
  "cnd1106": "physical_science",
  "dnd1106": "physical_science",
  "ccu1111": "physical_science",
  "dcu1111": "physical_science",
  "dhn1106": "physical_science",
  "810": "physical_science",
  "humananatomyandphysiology": "human_anatomy_and_physiology",
  "cnd1105": "human_anatomy_and_physiology",
  "dnd1105": "human_anatomy_and_physiology",
  "ccu1107": "human_anatomy_and_physiology",
  "dcu1107": "human_anatomy_and_physiology",
  "dndt1105": "human_anatomy_and_physiology",
  "humananatomy": "human_anatomy_and_physiology",
  "physiology": "human_anatomy_and_physiology",
  "910": "human_anatomy_and_physiology",
  "hivandaids": "hiv_and_aids",
  "cnd1102": "principles_of_human_nutrition",
  "dnd1102": "principles_of_human_nutrition",
  "ccu1104": "hiv_and_aids",
  "dcu1104": "hiv_and_aids",
  "dhn1107": "hiv_and_aids",
  "hivaids": "hiv_and_aids",
  "1010": "hiv_and_aids",
  "introductiontonutritionanddietetics": "introduction_to_nutrition_and_dietetics",
  "cnd1205": "introduction_to_nutrition_and_dietetics",
  "dnd1205": "introduction_to_nutrition_and_dietetics",
  "dhn1203": "introduction_to_nutrition_and_dietetics",
  "nutr101": "introduction_to_nutrition_and_dietetics",
  "nutr102": "introduction_to_nutrition_and_dietetics",
  "introductiontonutrition": "introduction_to_nutrition_and_dietetics",
  "1110": "introduction_to_nutrition_and_dietetics",
  "foodsafetyandhygiene": "food_safety_and_hygiene",
  "cnd1203": "food_safety_and_hygiene",
  "dnd1203": "food_safety_and_hygiene",
  "dhn1205": "food_safety_and_hygiene",
  "dndt1107": "food_safety_and_hygiene",
  "chn1203": "food_safety_and_hygiene",
  "foodsafetyhygiene": "food_safety_and_hygiene",
  "1210": "food_safety_and_hygiene",
  "foodproductioninvalids": "food_production_invalids",
  "cnd1204": "food_production_invalids",
  "dnd1204": "food_production_invalids",
  "dhn1206": "food_production_invalids",
  "dndt1101": "basic_biochemistry",
  "foodproductionforinvalidsandconvalescents": "food_production_invalids",
  "foodproductionforinvalids": "food_production_invalids",
  "foodproduction": "food_production_invalids",
  "1310": "food_production_invalids",
  "mealplanningmanagementservice": "meal_planning_management_service",
  "cnd1302": "meal_planning_management_service",
  "dnd1302": "meal_planning_management_service",
  "dhn1207": "meal_planning_management_service",
  "dndt1202": "meal_planning_management_service",
  "chn1302": "meal_planning_management_service",
  "mealplanningmanagementandservice": "meal_planning_management_service",
  "mealplanning": "meal_planning_management_service",
  "mealplanningandmanagement": "meal_planning_management_service",
  "1410": "meal_planning_management_service",
  "nutritionanthropology": "nutrition_anthropology",
  "cnd1304": "nutrition_anthropology",
  "dnd1304": "nutrition_anthropology",
  "dhn1208": "nutrition_anthropology",
  "chn1304": "nutrition_anthropology",
  "1510": "nutrition_anthropology",
  "diettherapyi": "diet_therapy_i",
  "cnd1202": "diet_therapy_i",
  "dnd1202": "diet_therapy_i",
  "dhn1209": "diet_therapy_i",
  "dndt1104": "diet_therapy_ii",
  "diet101": "diet_therapy_i",
  "diettherapy1": "diet_therapy_i",
  "diettherapy": "diet_therapy_i",
  "1610": "diet_therapy_i",
  "maternalandchildnutrition": "maternal_and_child_nutrition",
  "cnd1303": "maternal_and_child_nutrition",
  "dnd1303": "maternal_and_child_nutrition",
  "dhn1302": "maternal_and_child_nutrition",
  "chn1303": "maternal_and_child_nutrition",
  "1710": "maternal_and_child_nutrition",
  "nutritioninhivaids": "nutrition_in_hiv_aids",
  "cnd1301": "nutrition_in_hiv_aids",
  "dnd1301": "nutrition_in_hiv_aids",
  "dhn1303": "nutrition_in_hiv_aids",
  "chn1301": "nutrition_in_hiv_aids",
  "chn1201": "nutrition_in_hiv_aids",
  "nutritioninhivandaids": "nutrition_in_hiv_aids",
  "1810": "nutrition_in_hiv_aids",
  "legalaspectsnutrition": "legal_aspects_nutrition",
  "cnd1305": "legal_aspects_nutrition",
  "dnd1305": "legal_aspects_nutrition",
  "dhn1304": "legal_aspects_nutrition",
  "chn1305": "legal_aspects_nutrition",
  "legalaspectsofnutritionanddietetics": "legal_aspects_nutrition",
  "legalaspects": "legal_aspects_nutrition",
  "1910": "legal_aspects_nutrition",
  "principlesofhumannutrition": "principles_of_human_nutrition",
  "dhn1305": "principles_of_human_nutrition",
  "nutr103": "principles_of_human_nutrition",
  "chn1101": "principles_of_human_nutrition",
  "humannutrition": "principles_of_human_nutrition",
  "2010": "principles_of_human_nutrition",
  "industrialattachmenti": "industrial_attachment_i",
  "cnd1307": "industrial_attachment_i",
  "dnd1307": "industrial_attachment_i",
  "dhn1306": "industrial_attachment_i",
  "dndt1106": "food_processing_preservation",
  "industrialattachment1": "industrial_attachment_i",
  "attachmenti": "industrial_attachment_i",
  "2110": "industrial_attachment_i",
  "intromicrobiology": "intro_microbiology",
  "cnd2101": "intro_microbiology",
  "dnd2303": "intro_microbiology",
  "dhn2201": "intro_microbiology",
  "dndt1103": "intro_microbiology",
  "chn2101": "intro_microbiology",
  "introductiontomicrobiology": "intro_microbiology",
  "microbiology": "intro_microbiology",
  "2220": "intro_microbiology",
  "diettherapyii": "diet_therapy_ii",
  "cnd2201": "diet_therapy_ii",
  "dnd2105": "diet_therapy_ii",
  "dhn2205": "diet_therapy_ii",
  "diet201": "diet_therapy_ii",
  "diettherapy2": "diet_therapy_ii",
  "2320": "diet_therapy_ii",
  "foodprocessingpreservation": "food_processing_preservation",
  "cnd2202": "food_processing_preservation",
  "dnd2106": "food_processing_preservation",
  "dhn2204": "food_processing_preservation",
  "chn2203": "food_processing_preservation",
  "principlesoffoodprocessingandpreservation": "food_processing_preservation",
  "foodprocessingandpreservation": "food_processing_preservation",
  "foodprocessing": "food_processing_preservation",
  "2420": "food_processing_preservation",
  "introbiostatistics": "intro_biostatistics",
  "cnd2104": "intro_biostatistics",
  "dnd2304": "intro_biostatistics",
  "dhn2202": "intro_biostatistics",
  "dndt1102": "intro_biostatistics",
  "introductiontobiostatistics": "intro_biostatistics",
  "biostatistics": "intro_biostatistics",
  "2520": "intro_biostatistics",
  "basicbiochemistry": "basic_biochemistry",
  "cnd2105": "basic_biochemistry",
  "dnd2104": "basic_biochemistry",
  "dhn2101": "basic_biochemistry",
  "biochemistry": "basic_biochemistry",
  "2620": "basic_biochemistry",
  "nutritioninlifespan": "nutrition_in_lifespan",
  "cnd2103": "nutrition_in_lifespan",
  "dnd2203": "nutrition_in_lifespan",
  "dhn2203": "nutrition_in_lifespan",
  "chn2103": "nutrition_in_lifespan",
  "nutritioninthelifespan": "nutrition_in_lifespan",
  "lifespannutrition": "nutrition_in_lifespan",
  "2720": "nutrition_in_lifespan",
  "nutritionandbehaviour": "nutrition_and_behaviour",
  "cnd2204": "nutrition_and_behaviour",
  "dnd2204": "nutrition_and_behaviour",
  "dhn2207": "nutrition_and_behaviour",
  "chn2204": "nutrition_and_behaviour",
  "principlesofnutritionandbehaviour": "nutrition_and_behaviour",
  "2820": "nutrition_and_behaviour",
  "primaryhealthcare": "primary_health_care",
  "cnd2205": "primary_health_care",
  "dnd2201": "primary_health_care",
  "dhn2302": "primary_health_care",
  "chn2205": "primary_health_care",
  "introductiontoprimaryhealthcare": "primary_health_care",
  "phc": "primary_health_care",
  "2920": "primary_health_care",
  "firstaid": "first_aid",
  "cnd2102": "first_aid",
  "dnd2102": "first_aid",
  "dhn2305": "first_aid",
  "chn2102": "first_aid",
  "dnd210": "first_aid",
  "3020": "first_aid",
  "businessplan": "business_plan",
  "cnd2206": "business_plan",
  "dnd2305": "business_plan",
  "dhn2307": "business_plan",
  "chn2206": "business_plan",
  "3120": "business_plan",
  "researchmethods": "research_methods",
  "cnd2207": "research_methods",
  "dnd2306": "research_methods",
  "dhn2304": "research_methods",
  "dndt1206": "research_methods",
  "chn2207": "nutrition_assessment_surveillance",
  "3220": "research_methods",
  "industrialattachmentii": "industrial_attachment_ii",
  "cnd2307": "industrial_attachment_ii",
  "dnd2307": "industrial_attachment_ii",
  "dhn2306": "industrial_attachment_ii",
  "dnd3301": "industrial_attachment_ii",
  "chn2307": "industrial_attachment_ii",
  "industrialattachment2": "industrial_attachment_ii",
  "attachmentii": "industrial_attachment_ii",
  "3320": "industrial_attachment_ii",
  "foodmicrobiologyparasitology": "food_microbiology_parasitology",
  "dnd3103": "food_microbiology_parasitology",
  "dhn3103": "food_microbiology_parasitology",
  "dndt1302": "food_microbiology_parasitology",
  "foodmicrobiologyandparasitology": "food_microbiology_parasitology",
  "3430": "food_microbiology_parasitology",
  "communicablenoncommunicable": "communicable_non_communicable",
  "dnd3102": "communicable_non_communicable",
  "dnd3207": "communicable_non_communicable",
  "dhn3101": "communicable_non_communicable",
  "dhn2303": "communicable_non_communicable",
  "chn2309": "communicable_non_communicable",
  "communicableandnoncommunicablediseases": "communicable_non_communicable",
  "communicablenoncommunicablediseases": "communicable_non_communicable",
  "3530": "communicable_non_communicable",
  "foodsecurity": "food_security",
  "dnd3101": "food_security",
  "dhn3102": "food_security",
  "dndt1203": "food_security",
  "chn2302": "food_security",
  "3630": "food_security",
  "nutritioneducationcounselling": "nutrition_education_counselling",
  "dnd3204": "nutrition_education_counselling",
  "dhn3105": "nutrition_education_counselling",
  "dndt1301": "nutrition_education_counselling",
  "chn2304": "nutrition_in_emergencies",
  "nutritioneducationandcounselling": "nutrition_education_counselling",
  "nutritioneducation": "nutrition_education_counselling",
  "3730": "nutrition_education_counselling",
  "diettherapyiii": "diet_therapy_iii",
  "dnd3104": "diet_therapy_iii",
  "dhn3104": "diet_therapy_iii",
  "dndt1204": "diet_therapy_iii",
  "diet301": "diet_therapy_iii",
  "diettherapy3": "diet_therapy_iii",
  "3830": "diet_therapy_iii",
  "nutritionepidemiology": "nutrition_epidemiology",
  "dnd3203": "nutrition_epidemiology",
  "dhn3203": "nutrition_epidemiology",
  "dndt1303": "nutrition_epidemiology",
  "nutr301": "nutrition_epidemiology",
  "3930": "nutrition_epidemiology",
  "nutritioninemergencies": "nutrition_in_emergencies",
  "cnd2301": "nutrition_in_emergencies",
  "dnd2301": "nutrition_in_emergencies",
  "dhn3204": "nutrition_in_emergencies",
  "4030": "nutrition_in_emergencies",
  "communitypartnershipskills": "community_partnership_skills",
  "dnd3105": "community_partnership_skills",
  "dhn3206": "community_partnership_skills",
  "dndt1205": "community_partnership_skills",
  "communitypartnership": "community_partnership_skills",
  "4130": "community_partnership_skills",
  "nutritionassessmentsurveillance": "nutrition_assessment_surveillance",
  "cnd2302": "nutrition_assessment_surveillance",
  "dnd2302": "nutrition_assessment_surveillance",
  "dhn3106": "nutrition_assessment_surveillance",
  "nutritionassessmentandsurveillance": "nutrition_assessment_surveillance",
  "nutritionassessment": "nutrition_assessment_surveillance",
  "4230": "nutrition_assessment_surveillance",
  "productdevelopmentmarketingsales": "product_development_marketing_sales",
  "dnd3201": "product_development_marketing_sales",
  "dhn3201": "product_development_marketing_sales",
  "dndt1306": "product_development_marketing_sales",
  "productdevelopmentmarketingandsales": "product_development_marketing_sales",
  "productdevelopment": "product_development_marketing_sales",
  "4330": "product_development_marketing_sales",
  "industrialorganizationmanagement": "industrial_organization_management",
  "dnd3202": "industrial_organization_management",
  "dhn3202": "industrial_organization_management",
  "dndt1304": "industrial_organization_management",
  "industrialorganizationandmanagement": "industrial_organization_management",
  "industrialorganization": "industrial_organization_management",
  "4430": "industrial_organization_management",
  "tradeproject": "trade_project",
  "dnd3206": "trade_project",
  "dhn3205": "trade_project",
  "dndt1305": "trade_project",
  "cnd2306": "trade_project",
  "project": "trade_project",
  "researchproject": "trade_project",
  "4530": "trade_project"
};

/**
 * Normalizes any unit string (code, title, alias) into an alphanumeric lowercase lookup key.
 */
export function normalizeKey(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]/g, '');
}

/**
 * Resolves a unit code and/or unit name to its canonical curriculum key.
 */
export function resolveCanonicalKey(unitCode: string, unitName?: string): string | undefined {
  // 1. If unitName is provided, check if the normalized unitName matches directly
  if (unitName) {
    const normName = normalizeKey(unitName);
    if (SHARED_UNIT_ALIAS_MAP[normName]) {
      return SHARED_UNIT_ALIAS_MAP[normName];
    }
  }

  // 2. Check normalized unitCode
  if (unitCode) {
    const normCode = normalizeKey(unitCode);
    if (SHARED_UNIT_ALIAS_MAP[normCode]) {
      return SHARED_UNIT_ALIAS_MAP[normCode];
    }
  }

  // 3. Substring matching on unitName
  if (unitName) {
    const lowerName = unitName.toLowerCase();
    for (const [alias, key] of Object.entries(SHARED_UNIT_ALIAS_MAP)) {
      if (alias.length > 5 && lowerName.includes(alias)) {
        return key;
      }
    }
  }

  return undefined;
}
