/**
 * SHARED UNIT ALIAS MAP (CND <-> DND Harmonization)
 * Maps normalized unit codes and titles to canonical curriculum keys across all 3 modules.
 * Authoritative institutional mapping covering CND, DND, CCU, DCU, CHN, DHN, and DNDT programmes.
 */

export const SHARED_UNIT_ALIAS_MAP: Record<string, string> = {
  "informationcommunicationtechnology": "information_communication_technology",
  "ict": "information_communication_technology",
  "ictdigitalliteracy": "information_communication_technology",
  "digitalliteracy": "information_communication_technology",
  "computingskills": "information_communication_technology",
  "entrepreneurship": "entrepreneurship",
  "entrepreneurshipeducation": "entrepreneurship",
  "communicationskills": "communication_skills",
  "communication": "communication_skills",
  "lifeskills": "life_skills",
  "basicmathematics": "basic_mathematics",
  "mathematics": "basic_mathematics",
  "physicalscience": "physical_science",
  "physicalsciences": "physical_science",
  "appliedphysicalsciences": "physical_science",
  "appliedphysicalsciencesi": "physical_science",
  "appliedphysicalsciencesichemistry": "physical_science",
  "appliedphysicalsciencesii": "physical_science",
  "appliedphysicalsciencesiiphysics": "physical_science",
  "nutritionphysicalsciencesi": "physical_science",
  "appliedbiologicalsciences": "physical_science",
  "humananatomyandphysiology": "human_anatomy_and_physiology",
  "humananatomyphysiology": "human_anatomy_and_physiology",
  "humananatomy": "human_anatomy_and_physiology",
  "physiology": "human_anatomy_and_physiology",
  "medicalterms": "human_anatomy_and_physiology",
  "hivandaids": "hiv_and_aids",
  "hivaids": "hiv_and_aids",
  "hivaidsmanagement": "hiv_and_aids",
  "hivmanagement": "hiv_and_aids",
  "introductiontonutritionanddietetics": "introduction_to_nutrition_and_dietetics",
  "introductiontonutritiondietetics": "introduction_to_nutrition_and_dietetics",
  "introductiontonutrition": "introduction_to_nutrition_and_dietetics",
  "foodsafetyandhygiene": "food_safety_and_hygiene",
  "foodsafetyhygiene": "food_safety_and_hygiene",
  "foodsafety": "food_safety_and_hygiene",
  "foodhygiene": "food_safety_and_hygiene",
  "foodproductionforinvalidsandconvalescents": "food_production_invalids",
  "foodproductionforinvalidsandconvalescent": "food_production_invalids",
  "foodproductioninvalidsandconvalescents": "food_production_invalids",
  "foodproductionforinvalids": "food_production_invalids",
  "foodproductioninvalids": "food_production_invalids",
  "mealplanningmanagementservice": "meal_planning_management_service",
  "mealplanningmanagementandservice": "meal_planning_management_service",
  "mealplanningandmanagement": "meal_planning_management_service",
  "mealplanning": "meal_planning_management_service",
  "nutritionanthropology": "nutrition_anthropology",
  "diettherapyi": "diet_therapy_i",
  "diettherapy1": "diet_therapy_i",
  "diettherapy": "diet_therapy_i",
  "introductiontonutritioncareprocess": "diet_therapy_i",
  "nutritioncareprocess": "diet_therapy_i",
  "managementofmalnutrition": "diet_therapy_i",
  "maternalandchildnutrition": "maternal_and_child_nutrition",
  "maternalchildnutrition": "maternal_and_child_nutrition",
  "nutritioninhivaids": "nutrition_in_hiv_aids",
  "nutritioninhivandaids": "nutrition_in_hiv_aids",
  "legalaspectsofnutritionanddietetics": "legal_aspects_nutrition",
  "legalaspectsinnutritionanddietetics": "legal_aspects_nutrition",
  "legalaspectsnutrition": "legal_aspects_nutrition",
  "legalaspects": "legal_aspects_nutrition",
  "principlesofhumannutrition": "principles_of_human_nutrition",
  "humannutrition": "principles_of_human_nutrition",
  "industrialattachmenti": "industrial_attachment_i",
  "industrialattachment1": "industrial_attachment_i",
  "industrialattachment": "industrial_attachment_i",
  "industrialattachment1clinicalsetting": "industrial_attachment_i",
  "clinicalrotation": "industrial_attachment_i",
  "intromicrobiology": "intro_microbiology",
  "introductiontomicrobiology": "intro_microbiology",
  "microbiology": "intro_microbiology",
  "diettherapyii": "diet_therapy_ii",
  "diettherapy2": "diet_therapy_ii",
  "foodprocessingpreservation": "food_processing_preservation",
  "principlesoffoodprocessingandpreservation": "food_processing_preservation",
  "foodprocessingandpreservation": "food_processing_preservation",
  "foodprocessing": "food_processing_preservation",
  "foodscience": "food_processing_preservation",
  "introbiostatistics": "intro_biostatistics",
  "introductiontobiostatistics": "intro_biostatistics",
  "biostatistics": "intro_biostatistics",
  "basicbiochemistry": "basic_biochemistry",
  "biochemistryi": "basic_biochemistry",
  "biochemistryii": "basic_biochemistry",
  "biochemistry": "basic_biochemistry",
  "nutritioninthelifespan": "nutrition_in_lifespan",
  "nutritionlifespan": "nutrition_in_lifespan",
  "principlesofnutritionandbehaviour": "nutrition_and_behaviour",
  "principlesofnutritionandbehavior": "nutrition_and_behaviour",
  "introductiontobehavioralscience": "nutrition_and_behaviour",
  "nutritionandbehaviour": "nutrition_and_behaviour",
  "primaryhealthcare": "primary_health_care",
  "introductiontoprimaryhealthcare": "primary_health_care",
  "firstaid": "first_aid",
  "businessplan": "business_plan",
  "researchmethods": "research_methods",
  "industrialattachmentii": "industrial_attachment_ii",
  "industrialattachment2": "industrial_attachment_ii",
  "foodmicrobiologyparasitology": "food_microbiology_parasitology",
  "foodmicrobiologyandparasitology": "food_microbiology_parasitology",
  "communicablediseases": "communicable_non_communicable",
  "communicabledisease": "communicable_non_communicable",
  "noncommunicablediseases": "communicable_non_communicable",
  "noncommunicabledisease": "communicable_non_communicable",
  "communicableandnoncommunicablediseases": "communicable_non_communicable",
  "foodsecurity": "food_security",
  "agriculturalproduction": "food_security",
  "nutritioneducationandcounselling": "nutrition_education_counselling",
  "nutritioneducationandcounseling": "nutrition_education_counselling",
  "nutritioneducationcounseling": "nutrition_education_counselling",
  "demonstrationtechniques": "nutrition_education_counselling",
  "diettherapyiii": "diet_therapy_iii",
  "diettherapy3": "diet_therapy_iii",
  "nutritionepidemiology": "nutrition_epidemiology",
  "epidemiology": "nutrition_epidemiology",
  "nutritioninemergencies": "nutrition_in_emergencies",
  "emergencynutrition": "nutrition_in_emergencies",
  "communitypartnershipskills": "community_partnership_skills",
  "communitypartnership": "community_partnership_skills",
  "communitydiagnosisandmobilization": "community_partnership_skills",
  "communitydiagnosis": "community_partnership_skills",
  "nutritionassessmentandsurveillance": "nutrition_assessment_surveillance",
  "nutritionassessmentsurveillance": "nutrition_assessment_surveillance",
  "introductiontonutritionassessmentandsurveillance": "nutrition_assessment_surveillance",
  "nutritionforvulnerablegroups": "nutrition_assessment_surveillance",
  "productdevelopmentmarketingandsales": "product_development_marketing_sales",
  "productdevelopmentmarketingsales": "product_development_marketing_sales",
  "productdevelopment": "product_development_marketing_sales",
  "industrialorganizationandmanagement": "industrial_organization_management",
  "industrialorganizationmanagement": "industrial_organization_management",
  "industrialorganization": "industrial_organization_management",
  "tradeproject": "trade_project",
  "tradeprojectbusinessplan": "trade_project",
  "project": "trade_project",
  "ccu1101": "communication_skills",
  "ccu1104": "hiv_and_aids",
  "ccu1105": "entrepreneurship",
  "ccu1106": "information_communication_technology",
  "ccu1107": "human_anatomy_and_physiology",
  "ccu1110": "basic_mathematics",
  "ccu1111": "physical_science",
  "dcu1101": "communication_skills",
  "dcu1102": "information_communication_technology",
  "dcu1104": "first_aid",
  "dcu1105": "entrepreneurship",
  "dcu1106": "life_skills",
  "dcu1107": "human_anatomy_and_physiology",
  "dcu1110": "basic_mathematics",
  "dcu1111": "physical_science",
  "cnd1101": "communication_skills",
  "cnd1102": "entrepreneurship",
  "cnd1103": "life_skills",
  "cnd1104": "basic_mathematics",
  "cnd1105": "human_anatomy_and_physiology",
  "cnd1106": "physical_science",
  "cnd1201": "information_communication_technology",
  "cnd1202": "diet_therapy_i",
  "cnd1203": "food_safety_and_hygiene",
  "cnd1204": "food_production_invalids",
  "cnd1205": "legal_aspects_nutrition",
  "cnd1301": "nutrition_in_hiv_aids",
  "cnd1302": "meal_planning_management_service",
  "cnd1303": "maternal_and_child_nutrition",
  "cnd1304": "nutrition_anthropology",
  "cnd1306": "nutrition_anthropology",
  "cnd2101": "intro_microbiology",
  "cnd2102": "life_skills",
  "cnd2103": "industrial_attachment_i",
  "cnd2104": "intro_biostatistics",
  "cnd2105": "basic_biochemistry",
  "cnd2106": "food_processing_preservation",
  "cnd2107": "physical_science",
  "cnd2201": "diet_therapy_ii",
  "cnd2202": "food_processing_preservation",
  "cnd2306": "trade_project",
  "dnd105": "communication_skills",
  "dnd1101": "communication_skills",
  "dnd1102": "entrepreneurship",
  "dnd1103": "hiv_and_aids",
  "dnd1104": "principles_of_human_nutrition",
  "dnd1105": "human_anatomy_and_physiology",
  "dnd1106": "physical_science",
  "dnd1201": "information_communication_technology",
  "dnd1202": "diet_therapy_i",
  "dnd1203": "food_safety_and_hygiene",
  "dnd1204": "physical_science",
  "dnd1205": "legal_aspects_nutrition",
  "dnd1206": "diet_therapy_i",
  "dnd1301": "basic_mathematics",
  "dnd1302": "meal_planning_management_service",
  "dnd1303": "maternal_and_child_nutrition",
  "dnd1304": "food_production_invalids",
  "dnd1305": "nutrition_in_hiv_aids",
  "dnd1306": "nutrition_anthropology",
  "dnd1307": "primary_health_care",
  "dnd2101": "diet_therapy_i",
  "dnd2102": "life_skills",
  "dnd2103": "industrial_attachment_i",
  "dnd2104": "nutrition_in_lifespan",
  "dnd2105": "diet_therapy_ii",
  "dnd2106": "food_processing_preservation",
  "dnd2107": "first_aid",
  "dnd2201": "industrial_attachment_i",
  "dnd2301": "nutrition_in_emergencies",
  "dnd2302": "nutrition_assessment_surveillance",
  "dnd2303": "intro_microbiology",
  "dnd2304": "intro_biostatistics",
  "dnd2305": "basic_biochemistry",
  "dnd2306": "research_methods",
  "dnd2307": "nutrition_and_behaviour",
  "dnd3101": "food_security",
  "dnd3102": "communicable_non_communicable",
  "dnd3103": "food_microbiology_parasitology",
  "dnd3104": "diet_therapy_iii",
  "dnd3105": "community_partnership_skills",
  "dnd3106": "basic_biochemistry",
  "dnd3201": "product_development_marketing_sales",
  "dnd3202": "industrial_organization_management",
  "dnd3203": "nutrition_epidemiology",
  "dnd3204": "nutrition_education_counselling",
  "dnd3205": "food_security",
  "dnd3206": "trade_project",
  "dnd3207": "communicable_non_communicable",
  "dnd3301": "industrial_attachment_ii",
  "chn1101": "physical_science",
  "chn1201": "nutrition_in_hiv_aids",
  "chn1203": "food_safety_and_hygiene",
  "chn1301": "nutrition_in_hiv_aids",
  "chn1302": "meal_planning_management_service",
  "chn1303": "maternal_and_child_nutrition",
  "chn1304": "nutrition_anthropology",
  "chn1305": "legal_aspects_nutrition",
  "chn2101": "intro_microbiology",
  "chn2201": "nutrition_and_behaviour",
  "chn2203": "food_production_invalids",
  "chn2207": "nutrition_assessment_surveillance",
  "chn2304": "nutrition_in_emergencies",
  "chn2305": "community_partnership_skills",
  "chn2306": "nutrition_education_counselling",
  "chn2307": "nutrition_in_hiv_aids",
  "chn2308": "nutrition_assessment_surveillance",
  "chn2309": "food_security",
  "dhn1101": "communication_skills",
  "dhn1102": "information_communication_technology",
  "dhn1103": "entrepreneurship",
  "dhn1104": "life_skills",
  "dhn1105": "human_anatomy_and_physiology",
  "dhn1106": "physical_science",
  "dhn1107": "hiv_and_aids",
  "dhn1203": "introduction_to_nutrition_and_dietetics",
  "dhn1205": "food_safety_and_hygiene",
  "dhn1206": "food_production_invalids",
  "dhn1207": "meal_planning_management_service",
  "dhn1208": "nutrition_anthropology",
  "dhn1209": "diet_therapy_i",
  "dhn1301": "human_anatomy_and_physiology",
  "dhn1302": "nutrition_anthropology",
  "dhn1303": "legal_aspects_nutrition",
  "dhn1304": "maternal_and_child_nutrition",
  "dhn1305": "food_production_invalids",
  "dhn1306": "industrial_attachment_i",
  "dhn2101": "industrial_attachment_i",
  "dhn2201": "intro_microbiology",
  "dhn2202": "intro_biostatistics",
  "dhn2203": "basic_biochemistry",
  "dhn2204": "food_processing_preservation",
  "dhn2205": "diet_therapy_ii",
  "dhn2207": "primary_health_care",
  "dhn2302": "nutrition_in_lifespan",
  "dhn2303": "communicable_non_communicable",
  "dhn2304": "basic_biochemistry",
  "dhn2305": "nutrition_and_behaviour",
  "dhn2307": "research_methods",
  "dhn3101": "communicable_non_communicable",
  "dhn3102": "food_security",
  "dhn3103": "food_microbiology_parasitology",
  "dhn3104": "diet_therapy_iii",
  "dhn3105": "nutrition_education_counselling",
  "dhn3106": "nutrition_assessment_surveillance",
  "dhn3201": "product_development_marketing_sales",
  "dhn3202": "industrial_organization_management",
  "dhn3203": "nutrition_epidemiology",
  "dhn3204": "nutrition_in_emergencies",
  "dhn3205": "trade_project",
  "dhn3206": "community_partnership_skills",
  "dndt1101": "first_aid",
  "dndt1102": "intro_biostatistics",
  "dndt1103": "intro_microbiology",
  "dndt1104": "diet_therapy_ii",
  "dndt1105": "basic_biochemistry",
  "dndt1106": "food_processing_preservation",
  "dndt1107": "research_methods",
  "dndt1201": "communicable_non_communicable",
  "dndt1202": "nutrition_and_behaviour",
  "dndt1203": "food_security",
  "dndt1204": "diet_therapy_iii",
  "dndt1205": "community_partnership_skills",
  "dndt1206": "communicable_non_communicable",
  "dndt1207": "basic_biochemistry",
  "dndt1301": "nutrition_education_counselling",
  "dndt1302": "food_microbiology_parasitology",
  "dndt1303": "nutrition_epidemiology",
  "dndt1304": "industrial_organization_management",
  "dndt1305": "trade_project",
  "dndt1306": "product_development_marketing_sales",
  "dndt2101": "industrial_attachment_i"
};

/**
 * Normalizes any unit string (code, title, alias) into an alphanumeric lowercase lookup key.
 */
export function normalizeKey(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]/g, '');
}

/**
 * Resolves a unit code and/or unit name to its canonical curriculum key.
 * Prioritizes exact semantic title matching before code matching to avoid
 * cross-department code numbering collisions.
 */
export function resolveCanonicalKey(unitCode: string, unitName?: string): string | undefined {
  // 1. Priority 1: Exact normalized title match
  if (unitName) {
    const normName = normalizeKey(unitName);
    if (SHARED_UNIT_ALIAS_MAP[normName]) {
      return SHARED_UNIT_ALIAS_MAP[normName];
    }
  }

  // 2. Priority 2: Substring matching on unitName
  if (unitName) {
    const normName = normalizeKey(unitName);
    for (const [alias, key] of Object.entries(SHARED_UNIT_ALIAS_MAP)) {
      if (alias.length > 5 && (normName.includes(alias) || alias.includes(normName))) {
        return key;
      }
    }
  }

  // 3. Priority 3: Exact normalized unitCode match
  if (unitCode) {
    const normCode = normalizeKey(unitCode);
    if (SHARED_UNIT_ALIAS_MAP[normCode]) {
      return SHARED_UNIT_ALIAS_MAP[normCode];
    }
  }

  return undefined;
}
