import os

SUPABASE_URL = os.environ["SUPABASE_URL"].rstrip("/")
SUPABASE_SERVICE_ROLE_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
NOTES_ENGINE_TOKEN = os.environ["NOTES_ENGINE_TOKEN"]
MAX_SOURCE_BYTES = int(os.getenv("ENGINE_MAX_SOURCE_BYTES", str(150 * 1024 * 1024)))
MAX_OUTPUT_BYTES = int(os.getenv("ENGINE_MAX_OUTPUT_BYTES", str(50 * 1024 * 1024)))
