import type { Metadata } from 'next';
import { AlertTriangle, ArrowLeft, BookOpenCheck, CheckCircle2, GitMerge, Users } from 'lucide-react';
import Link from 'next/link';
import { Alert } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { EmptyState } from '@/components/ui/empty-state';
import { Input } from '@/components/ui/input';
import { MetricCard } from '@/components/ui/metric-card';
import { PageHeader } from '@/components/ui/page-header';
import { SectionHeader } from '@/components/ui/section-header';
import { Select } from '@/components/ui/select';
import { createClient } from '@/lib/supabase/server';
import { confirmSharedOfferingAction, generateCurrentOfferingsAction, reconcilePreviousAssignmentsAction, reserveOfferingWithoutTrainerAction } from '@/features/teaching-allocations/simple-allocation-actions';
import { FixedScheduleForm } from '@/features/teaching-allocations/fixed-schedule-form';
import { allocationMatchesOffering } from '@/features/teaching-allocations/allocation-reconciliation';
import { buildSharedClassMatchKey, canonicalizeSharedUnitTitle } from '@/features/teaching-allocations/shared-class-matching';
import { UnassignAllocationForm } from '@/features/teaching-allocations/unassign-allocation-form';
import { filterTrainersWithAllocations } from '@/features/teaching-allocations/trainer-allocation-filter';
import { AssignOfferingForm } from '@/features/teaching-allocations/assign-offering-form';
import { prioritizeActiveAcademicPeriods, resolveAcademicPeriodId } from '@/features/academic-periods/selection';
import { requireHodAccess } from '@/features/auth/authorization';

export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Simple teaching allocation' };
type Period={id:string;name:string;code:string;status:'planned'|'active'};
type Trainer={id:string;full_name:string;staff_number:string;home_department:string|null;department_id:string|null;normal_weekly_hours:number;workload_role:'hod'|'course_coordinator'|'full_time_trainer'|'part_time'|'external';availability_mode:'generally_available'|'selected_slots_only'};
type TrainerWorkload={trainer_id:string;allocated_hours:number|string;department_count:number|string};
type EquivalenceMember={equivalence_group_id:string;status:string};
type UnitSummary={code:string;name:string;weekly_sessions?:number|null;department_id:string|null;owning_department:string|null;is_service_unit:boolean;departments:{name:string}|null;unit_equivalence_members:EquivalenceMember|EquivalenceMember[]|null};
type Offering={id:string;cohort_id:string;unit_id:string;allocation_status:string;is_provisionally_reserved:boolean;confirmed_shared_offering_id:string|null;fixed_working_day_id:string|null;fixed_time_slot_id:string|null;weekly_sessions:number|null;session_duration_minutes:number|null;is_full_day_session:boolean;unit_offering_fixed_slots:{working_day_id:string;time_slot_id:string;sequence_number:number}[]|null;cohorts:{code:string;name:string;actual_size:number;programmes:{department_id:string}|null}|null;units:UnitSummary|null};
type Day={id:string;day_of_week:string}; type Slot={id:string;name:string;starts_at:string;ends_at:string;sequence_number:number};
type Allocation={id:string;cohort_id:string;unit_id:string;trainer_id:string|null;teaching_offering_id:string|null;source_unit_offering_id:string|null;participant_cohort_ids:string[]|null;weekly_sessions:number;session_duration_minutes:number;status:'draft'|'active';trainers:{full_name:string;staff_number:string}|null;units:UnitSummary|null;cohorts:{code:string;name:string;programmes:{department_id:string}|null}|null;scheduled_sessions:{id:string;status:string;is_locked:boolean}[]|null};
const fmt=(n:number)=>Number.isInteger(n)?String(n):n.toFixed(1);
const isClinicalRotationTitle=(value:string)=>/^clinical rotations?(?: (?:[ivx]+|\d+))?$/.test(value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim());
const getApprovedEquivalence=(unit:UnitSummary|null)=>{
 const members=unit?.unit_equivalence_members;
 if(!members)return null;
 const values=Array.isArray(members)?members:[members];
 return values.find(member=>member.status==='approved')?.equivalence_group_id??null;
};
const getUnitOwnershipLabel=(unit:UnitSummary|null,activeDepartmentId:string|null)=>{
 if(!unit)return null;
 const owner=unit.departments?.name??unit.owning_department;
 if(unit.department_id&&activeDepartmentId&&unit.department_id!==activeDepartmentId)return `Service unit from ${owner??'another department'}`;
 if(unit.is_service_unit)return owner?`Service unit · ${owner}`:'Service unit';
 return null;
};
const getOfferingWeeklySessions=(o:Offering)=>o.is_full_day_session?1:Math.max(o.weekly_sessions??1,o.units?.weekly_sessions??1);

export default async function Page({searchParams}:{searchParams:Promise<{period?:string;q?:string;allocationTrainer?:string;allocationQ?:string;allocationError?:string;assigned?:string;availabilityTrainer?:string;availabilityPeriod?:string;availabilitySaved?:string;reservationSaved?:string;unassigned?:string;unassignError?:string;reconciled?:string;merged?:string;restored?:string;review?:string;reconciliationError?:string;generated?:string;created?:string;autoMerged?:string;mergedUnits?:string;mergeSkipped?:string}>}) {
 const db=await createClient(); const params=await searchParams;
 const profile=await requireHodAccess();
 const [{data:periods},{data:trainers}]=await Promise.all([
  db.from('academic_periods').select('id,name,code,status').in('status',['planned','active']).order('starts_on',{ascending:false}),
  db.from('trainers').select('id,full_name,staff_number,home_department,department_id,normal_weekly_hours,workload_role,availability_mode').eq('is_active',true).eq('is_timetable_available',true).order('full_name')]);
 const selectablePeriods=prioritizeActiveAcademicPeriods((periods??[]) as Period[]);
 const period=resolveAcademicPeriodId(selectablePeriods,params.period);
 const empty=Promise.resolve({data:[]});
 const [{data:offerings},{data:days},{data:slots},{data:allocations},{data:institutionWorkloads}]=await Promise.all([
  period&&profile.activeDepartmentId?db.from('unit_offerings').select('id,cohort_id,unit_id,allocation_status,is_provisionally_reserved,confirmed_shared_offering_id,fixed_working_day_id,fixed_time_slot_id,weekly_sessions,session_duration_minutes,is_full_day_session,unit_offering_fixed_slots(working_day_id,time_slot_id,sequence_number),cohorts!inner(code,name,actual_size,programmes!inner(department_id)),units(code,name,weekly_sessions,department_id,owning_department,is_service_unit,departments(name),unit_equivalence_members(equivalence_group_id,status))').eq('academic_period_id',period).eq('cohorts.programmes.department_id',profile.activeDepartmentId).eq('approval_status','approved').eq('selection_state','included').eq('is_timetable_enabled',true).order('allocation_status'):empty,
  period?db.from('working_days').select('id,day_of_week').eq('academic_period_id',period).eq('is_enabled',true).order('sequence_number'):empty,
  period?db.from('time_slots').select('id,name,starts_at,ends_at,sequence_number').eq('academic_period_id',period).eq('is_enabled',true).eq('slot_type','teaching').order('sequence_number'):empty,
  period&&profile.activeDepartmentId?db.from('teaching_allocations').select('id,cohort_id,unit_id,trainer_id,teaching_offering_id,source_unit_offering_id,participant_cohort_ids,weekly_sessions,session_duration_minutes,status,trainers(full_name,staff_number),units(code,name,department_id,owning_department,is_service_unit,departments(name)),cohorts!inner(code,name,programmes!inner(department_id)),scheduled_sessions(id,status,is_locked),source_unit_offering:unit_offerings!teaching_allocations_source_unit_offering_id_fkey!inner(approval_status,selection_state,is_timetable_enabled)').eq('academic_period_id',period).eq('cohorts.programmes.department_id',profile.activeDepartmentId).eq('source_unit_offering.approval_status','approved').eq('source_unit_offering.selection_state','included').eq('source_unit_offering.is_timetable_enabled',true).in('status',['draft','active']).order('created_at',{ascending:false}):empty,
  period?db.rpc('get_institution_trainer_workloads',{target_academic_period_id:period}):empty]);
 const currentAllocations=(allocations??[]) as unknown as Allocation[]; const allTrainers=(trainers??[]) as Trainer[]; const trainersWithAllocations=filterTrainersWithAllocations(allTrainers,currentAllocations); const globalWorkloads=(institutionWorkloads??[]) as TrainerWorkload[]; const loads=new Map(globalWorkloads.map(item=>[item.trainer_id,Number(item.allocated_hours)]));
 const all=(offerings??[]) as unknown as Offering[];
 const hasAssignedTrainer=(offering:Offering)=>currentAllocations.some(allocation=>Boolean(allocation.trainer_id)&&allocationMatchesOffering({teachingOfferingId:offering.confirmed_shared_offering_id,participants:[{cohortId:offering.cohort_id,unitId:offering.unit_id,unitOfferingId:offering.id}],title:offering.units?.name??'',sessionDurationMinutes:offering.session_duration_minutes??120},{teachingOfferingId:allocation.teaching_offering_id,sourceUnitOfferingId:allocation.source_unit_offering_id,cohortId:allocation.cohort_id,unitId:allocation.unit_id,participantCohortIds:allocation.participant_cohort_ids??[allocation.cohort_id],unitTitle:allocation.units?.name??null,sessionDurationMinutes:allocation.session_duration_minutes}));
 const open=all.filter(o=>o.allocation_status==='unallocated'&&!hasAssignedTrainer(o)); const searchTerm=(params.q??'').trim(); const searchText=searchTerm.toLowerCase();
 const suggestionMap=new Map<string,Offering[]>();
 // Keep approved equivalents grouped together so they can be merged into a shared delivery regardless of temporary session format differences.
 for(const item of open){const equivalence=getApprovedEquivalence(item.units);const sessionKind=item.is_full_day_session?'full-day':'standard';const key=equivalence?`equiv:${equivalence}`:(item.units?.name?`name:${canonicalizeSharedUnitTitle(item.units.name)}:${sessionKind}`:null);if(!key)continue;const group=suggestionMap.get(key)??[];group.push(item);suggestionMap.set(key,group);}
 const suggestions=[...suggestionMap.values()].filter(group=>{const classKeys=new Set(group.map(item=>item.confirmed_shared_offering_id??item.id));const confirmedGroups=new Set(group.map(item=>item.confirmed_shared_offering_id).filter((value):value is string=>Boolean(value)));return group.every(item=>!item.is_provisionally_reserved)&&classKeys.size>1&&confirmedGroups.size<=1;});
 const representatives=open.filter((o,index)=>!o.confirmed_shared_offering_id||open.findIndex(x=>x.confirmed_shared_offering_id===o.confirmed_shared_offering_id)===index);
 const matchesSearch=(offering:Offering)=>[offering.units?.code,offering.units?.name,offering.cohorts?.code,offering.cohorts?.name].some(value=>value?.toLowerCase().includes(searchText));
 const visibleOpen=searchText?representatives.filter(offering=>{const members=offering.confirmed_shared_offering_id?open.filter(item=>item.confirmed_shared_offering_id===offering.confirmed_shared_offering_id):[offering];return members.some(matchesSearch);}):representatives;
 const allocationTrainer=params.allocationTrainer??''; const allocationQuery=(params.allocationQ??'').trim(); const allocationSearch=allocationQuery.toLowerCase(); const visibleAllocations=currentAllocations.filter(allocation=>(!allocationTrainer||allocation.trainer_id===allocationTrainer)&&(!allocationSearch||[allocation.trainers?.full_name,allocation.trainers?.staff_number,allocation.units?.code,allocation.units?.name,allocation.cohorts?.code,allocation.cohorts?.name].some(value=>value?.toLowerCase().includes(allocationSearch))));
 const returnParams=new URLSearchParams(); if(period)returnParams.set('period',period); if(searchTerm)returnParams.set('q',searchTerm); const returnTo=`/timetable/teaching-allocations?${returnParams.toString()}`;
 return <div className="space-y-5">
  <PageHeader
    eyebrow="Timetable preparation"
    title="Simple teaching allocation"
    description="Approve cohort offerings, confirm reviewed equivalent classes, then assign one trainer per delivery."
    actions={
      <div className="flex flex-wrap items-center gap-2">
        <Link
          href="/timetable/unit-equivalence"
          className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-border-strong bg-white px-3 text-xs font-semibold text-text-secondary hover:bg-surface-subtle"
        >
          <GitMerge className="size-3.5 text-primary" aria-hidden="true" />
          Unit equivalence
        </Link>
        <Link
          href="/dashboard"
          className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-border-strong bg-white px-3 text-xs font-semibold text-text-secondary hover:bg-surface-subtle"
        >
          <ArrowLeft className="size-3.5" aria-hidden="true" />
          Dashboard
        </Link>
      </div>
    }
  />
  {params.generated==='1'?<Alert variant="success" icon={CheckCircle2} title="Cohort offering recommendations generated"><p>{params.created??'0'} new recommendation(s) were created. Review and approve them under Units on offer before allocation.</p></Alert>:null}
  {params.allocationError?<Alert variant="danger" icon={AlertTriangle} title="The timetable change was not saved"><p>{params.allocationError}</p>{params.availabilityTrainer&&params.availabilityPeriod?<a href={`/timetable/trainers/availability?trainer=${encodeURIComponent(params.availabilityTrainer)}&period=${encodeURIComponent(params.availabilityPeriod)}&returnTo=${encodeURIComponent(returnTo)}`} className="mt-2 inline-flex h-9 items-center rounded-xl border border-danger-border bg-surface px-3 text-sm font-semibold text-danger">Set trainer availability</a>:null}</Alert>:null}
  {params.assigned==='1'?<Alert variant="success" icon={CheckCircle2}>Trainer assigned successfully. The unit has moved to Current trainer allocations.</Alert>:null}
  {params.availabilitySaved==='1'?<Alert variant="success" icon={CheckCircle2}>Trainer availability saved. Select the trainer and assign the unit again.</Alert>:null}
  {params.reservationSaved==='1'?<Alert variant="success" icon={CheckCircle2}>Unit included in timetable generation. The trainer remains unassigned.</Alert>:null}
  {params.unassigned==='1'?<Alert variant="success" icon={CheckCircle2}>Trainer unassigned from the live draft. The unit is available for allocation again, and the published timetable remains unchanged until the next version is published.</Alert>:null}
  {params.reconciled==='1'?<Alert variant="success" icon={CheckCircle2} title="Separated and previous assignments checked"><p>{params.merged??'0'} pending duplicate(s) rejoined to their assigned shared class. {params.restored??'0'} historical assignment(s) restored. {params.review??'0'} unit(s) remain for manual review.</p>{Number(params.merged??0)>0?<p className="mt-1 font-medium">Generate the draft timetable again so repaired shared classes receive a conflict-free placement.</p>:null}</Alert>:null}
  {params.reconciliationError?<Alert variant="danger" icon={AlertTriangle} title="Previous assignments were not reconciled">{params.reconciliationError}</Alert>:null}
  {params.unassignError?<Alert variant="danger" icon={AlertTriangle} title="The trainer was not unassigned">{params.unassignError}</Alert>:null}
  <Card className="p-4"><div className="flex flex-wrap items-end gap-3">
   <form method="get" className="flex items-end gap-2"><label className="space-y-1.5 text-sm font-medium">Academic Period<Select name="period" defaultValue={period} className="mt-1.5">{selectablePeriods.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name} ({p.status==='active'?'Active':'Planned'})</option>)}</Select></label><Button type="submit" variant="outline">Load</Button></form>
   <form action={generateCurrentOfferingsAction}><input type="hidden" name="academicPeriodId" value={period}/><Button type="submit" disabled={!period}>Generate offering recommendations</Button></form>
   <form action={reconcilePreviousAssignmentsAction}><input type="hidden" name="academicPeriodId" value={period}/><Button type="submit" variant="outline" disabled={!period}>Repair separated allocations</Button></form>
  </div></Card>
  <section className="grid gap-3 grid-cols-1 sm:grid-cols-3 xl:max-w-5xl">
   <MetricCard icon={BookOpenCheck} value={String(open.length)} label="Units awaiting trainer" description="Open units needing a trainer assigned"/>
   <MetricCard icon={Users} value={String((trainers??[]).length)} label="Available trainers" description="Active trainers in the institution pool"/>
   <MetricCard icon={BookOpenCheck} value={String(all.length-open.length)} label="Allocated and blocked" description="Units with a trainer or otherwise settled"/>
  </section>
  <section className="space-y-3">
  <SectionHeader title="Current trainer allocations" description="Review every active unit allocation and return incorrect assignments to the queue." actions={<form method="get" className="flex flex-wrap items-end gap-2"><input type="hidden" name="period" value={period}/><input type="hidden" name="q" value={searchTerm}/><label className="space-y-1.5 text-sm font-medium">Trainer<Select name="allocationTrainer" defaultValue={allocationTrainer} className="mt-1.5"><option value="">All allocated trainers</option>{trainersWithAllocations.map(trainer=><option key={trainer.id} value={trainer.id}>{trainer.full_name}</option>)}</Select></label><label className="space-y-1.5 text-sm font-medium">Find allocation<Input name="allocationQ" type="search" defaultValue={allocationQuery} placeholder="Unit, code or cohort" className="mt-1.5"/></label><Button type="submit" variant="outline">View</Button>{allocationTrainer||allocationQuery?<Button asChild variant="ghost"><a href={`/timetable/teaching-allocations?period=${encodeURIComponent(period)}`}>Clear</a></Button>:null}</form>}/>
  {visibleAllocations.length===0?<EmptyState icon={Users} title="No allocations found" description="No current allocations found for this selection."/>:<div className="overflow-hidden rounded-xl border border-border bg-surface"><table className="w-full table-fixed text-left text-sm"><thead className="border-b border-border bg-surface-subtle text-xs font-semibold uppercase tracking-wide text-text-muted"><tr><th className="min-w-0 break-words px-3 py-2.5">Trainer</th><th className="min-w-0 break-words px-3 py-2.5">Unit</th><th className="min-w-0 break-words px-3 py-2.5">Cohort</th><th className="min-w-0 break-words px-3 py-2.5">Weekly load</th><th className="min-w-0 break-words px-3 py-2.5">Timetable</th><th className="min-w-0 break-words px-3 py-2.5 text-right">Action</th></tr></thead><tbody className="divide-y divide-border-soft">{visibleAllocations.map(allocation=>{const isClinical=isClinicalRotationTitle(allocation.units?.name??'')||allocation.session_duration_minutes===480;const hours=isClinical?2.0:(allocation.weekly_sessions*allocation.session_duration_minutes/60);const activeSessions=(allocation.scheduled_sessions??[]).filter(session=>!['cancelled','archived'].includes(session.status));const unitLabel=`${allocation.units?.code??'Unit'} — ${allocation.units?.name??'Untitled unit'}`;const ownershipLabel=getUnitOwnershipLabel(allocation.units,profile.activeDepartmentId);return <tr key={allocation.id} className={allocation.trainer_id?'':'bg-warning-surface'}><td className="min-w-0 break-words px-3 py-2.5"><p className={`font-semibold ${allocation.trainer_id?'':'text-warning'}`}>{allocation.trainers?.full_name??'Unassigned trainer'}</p>{!allocation.trainer_id ? (
  <p className="text-[11px] text-text-muted xl:text-xs">
    Assign before publication
  </p>
) : null}</td><td className="min-w-0 break-words px-3 py-2.5"><p className="font-medium text-text-primary text-[13px] xl:text-sm">{allocation.units?.name??'Untitled unit'}</p><div className="flex flex-wrap items-center gap-1.5 mt-0.5 text-[11px] text-text-muted"><span>{allocation.units?.code}</span>{allocation.teaching_offering_id?(<><span>·</span><span className="text-primary font-medium">Shared class · {allocation.participant_cohort_ids?.length??1} cohorts</span></>):null}{ownershipLabel?(<><span>·</span><span className="font-medium text-warning">{ownershipLabel}</span></>):null}</div></td><td className="min-w-0 break-words px-3 py-2.5"><p className="text-xs text-text-muted">{allocation.cohorts?.name??'—'}</p></td><td className="min-w-0 break-words px-3 py-2.5"><p className="font-medium">{fmt(hours)}h</p><p className="text-xs text-text-muted">{isClinical?'1 × 480 min · 2.0h supervision':`${allocation.weekly_sessions} × ${allocation.session_duration_minutes} min`}</p></td><td className="min-w-0 break-words px-3 py-2.5"><p>{activeSessions.length>0?`${activeSessions.length} session${activeSessions.length===1?'':'s'}`:'Not generated'}</p>{activeSessions.some(session=>session.is_locked||session.status==='locked')?<p className="text-xs font-medium text-warning">Locked</p>:null}</td><td className="min-w-0 break-words px-3 py-2.5 text-right"><UnassignAllocationForm allocationId={allocation.id} academicPeriodId={period} allocationTrainer={allocationTrainer} allocationQuery={allocationQuery} unitLabel={unitLabel}/></td></tr>})}</tbody></table></div>}
  </section>
  {suggestions.length>0?<section className="space-y-3"><SectionHeader title="Approved equivalents available for shared delivery" description="These units share one reviewed canonical subject. Confirm the period-specific shared class after checking its schedule and combined size."/>{suggestions.map(group=>{const sessionCounts=group.map(getOfferingWeeklySessions);const highestSessions=Math.max(...sessionCounts);const countsDiffer=new Set(sessionCounts).size>1;return <form key={group.map(x=>x.id).join(':')} action={confirmSharedOfferingAction} className="rounded-2xl border border-warning-border bg-warning-surface p-4"><input type="hidden" name="academicPeriodId" value={period}/><input type="hidden" name="searchQuery" value={searchTerm}/><div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-text-primary">{group.map(x=>x.units?.name).filter((value,index,values)=>value&&values.indexOf(value)===index).join(' / ')}</p><p className="mt-1 text-sm text-text-muted">{group.map(x=>x.cohorts?.code).join(' + ')} · Combined learners {group.reduce((sum,x)=>sum+(x.cohorts?.actual_size??0),0)} · {highestSessions} shared session(s){countsDiffer?' · highest requirement used':''}</p>{group.map(x=><input key={x.id} type="hidden" name="offeringId" value={x.id}/>)}</div><Button type="submit">Confirm shared delivery</Button></div></form>})}</section>:null}
  <section className="space-y-3"><SectionHeader title="Trainer workload"/>{trainersWithAllocations.length===0?<EmptyState icon={Users} title="No trainer workload yet" description="No trainers have allocations for this Academic Period."/>:<div className="grid gap-3 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4 2xl:grid-cols-5 min-[1920px]:grid-cols-6">{trainersWithAllocations.map(t=>{const load=loads.get(t.id)??0,target=Number(t.normal_weekly_hours),extra=Math.max(0,load-target),remaining=Math.max(0,target-load),role={hod:'HOD',course_coordinator:'Course coordinator',full_time_trainer:'Full-time',part_time:'Part-time',external:'External'}[t.workload_role];const isGuest=profile&&t.department_id!==profile.activeDepartmentId;return <Card key={t.id} className="p-3 xl:p-3.5"><div className="flex justify-between gap-3"><div><p className="text-[13px] font-semibold leading-5 text-text-primary xl:text-sm 2xl:text-[15px]">{t.full_name}</p><p className="text-[11px] text-text-muted xl:text-xs">{isGuest?`Guest · ${t.home_department??'Other dept'}`:role}</p></div><span className="shrink-0 text-[12px] font-semibold text-text-primary xl:text-[13px] 2xl:text-sm">{isGuest?`${fmt(load)}h total`:`${fmt(load)} / ${fmt(target)}h`}</span></div>{!isGuest?(<><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-surface-subtle"><div className={`h-full ${extra>0?'bg-warning':'bg-primary'}`} style={{width:`${Math.min(100,target>0?load/target*100:0)}%`}}/></div>{extra>0?<p className="mt-2 flex items-center gap-1 text-xs font-medium text-warning"><AlertTriangle className="size-3"/>+{fmt(extra)}h extra</p>:<p className="mt-2 text-[11px] font-medium text-text-muted xl:text-xs">{remaining > 0 ? `${fmt(remaining)}h remaining` : 'Target met'}</p>}</>):(<p className="mt-2 text-[11px] font-medium text-text-muted xl:text-xs">Allocated from other departments</p>)}</Card>})}</div>}</section>
  <section className="space-y-3"><SectionHeader title="Units awaiting allocation" description="Assign a trainer now, or include the unit as unassigned and complete the trainer later." actions={<form method="get" className="flex w-full max-w-xl flex-wrap items-center gap-2"><input type="hidden" name="period" value={period}/><label htmlFor="allocation-unit-search" className="sr-only">Search units awaiting allocation</label><Input id="allocation-unit-search" name="q" type="search" defaultValue={searchTerm} placeholder="Search unit code, name or cohort" className="min-w-0 flex-1"/><Button type="submit">Search</Button>{searchTerm?<Button asChild variant="outline"><a href={`/timetable/teaching-allocations?period=${encodeURIComponent(period)}`}>Clear</a></Button>:null}</form>}/>{searchTerm?<p className="text-sm text-text-muted">{visibleOpen.length} result(s) for &quot;{searchTerm}&quot;</p>:null}
  {open.length===0?<EmptyState icon={BookOpenCheck} title="No units awaiting allocation" description="No unallocated units. Generate units from active cohorts or select another period."/>:visibleOpen.length===0?<EmptyState icon={BookOpenCheck} title="No matching units" description={`No units match "${searchTerm}". Try a unit code, unit name, or cohort.`}/>:<div className="space-y-3">{visibleOpen.map(o=>{const members=o.confirmed_shared_offering_id?open.filter(x=>x.confirmed_shared_offering_id===o.confirmed_shared_offering_id):[o];const fixedPatterns=(o.unit_offering_fixed_slots??[]).slice().sort((first,second)=>first.sequence_number-second.sequence_number);const fixedSlotIds=fixedPatterns.map(item=>item.time_slot_id);const fixedWorkingDayIds=fixedPatterns.map(item=>item.working_day_id);const ownershipLabel=getUnitOwnershipLabel(o.units,profile.activeDepartmentId);if(fixedSlotIds.length===0&&o.fixed_time_slot_id){fixedSlotIds.push(o.fixed_time_slot_id);if(o.fixed_working_day_id)fixedWorkingDayIds.push(o.fixed_working_day_id);}const effectiveSessions=getOfferingWeeklySessions(o);return <Card key={o.id} className={`p-4 ${o.is_provisionally_reserved?'border-warning-border bg-warning-surface':''}`}><div className="grid gap-4 lg:grid-cols-[1fr_1.3fr]"><div><p className="text-sm font-semibold">{o.units?.code} — {o.units?.name}</p><p className="mt-1 text-xs text-text-muted">{members.map(x=>x.cohorts?.code).join(' + ')} · {members.length>1?'Shared class · ':''}{effectiveSessions} session(s)</p>{ownershipLabel?<p className="mt-1 text-xs font-semibold text-warning">{ownershipLabel}</p>:null}{o.is_provisionally_reserved?<p className="mt-2 text-xs font-semibold text-warning">Included · trainer pending</p>:null}</div><div className="space-y-2.5">
    <FixedScheduleForm key={`${o.id}:${o.is_full_day_session}:${o.session_duration_minutes??120}:${o.fixed_working_day_id??''}:${fixedWorkingDayIds.join(':')}:${fixedSlotIds.join(':')}:${effectiveSessions}`} offeringId={o.id} academicPeriodId={period} searchQuery={searchTerm} weeklySessions={effectiveSessions} days={(days??[]) as Day[]} slots={(slots??[]) as Slot[]} fixedDayId={o.fixed_working_day_id} fixedWorkingDayIds={fixedWorkingDayIds} fixedSlotIds={fixedSlotIds} isFullDaySession={o.is_full_day_session} isClinicalRotation={isClinicalRotationTitle(o.units?.name??'')}/>
    <div className="grid min-w-0 gap-2 lg:grid-cols-[minmax(0,1fr)_auto]"><AssignOfferingForm offeringId={o.id} academicPeriodId={period} searchQuery={searchTerm} trainers={allTrainers.map(t=>{const load=loads.get(t.id)??0,target=Number(t.normal_weekly_hours),extra=Math.max(0,load-target),home=t.home_department?` · ${t.home_department}`:'',availability=t.availability_mode==='selected_slots_only'?' · selected times':'';const isGuest=profile&&t.department_id!==profile.activeDepartmentId;const workloadLabel=isGuest?`${fmt(load)}h allocated`:`${fmt(load)}/${fmt(target)}h${extra>0?` (+${fmt(extra)}h extra)`:''}`;return {id:t.id,label:`${t.full_name}${home} — ${workloadLabel}${availability}`};})}/><form action={reserveOfferingWithoutTrainerAction}><input type="hidden" name="offeringId" value={o.id}/><input type="hidden" name="academicPeriodId" value={period}/><input type="hidden" name="searchQuery" value={searchTerm}/><Button type="submit" disabled={o.is_provisionally_reserved} variant="outline" className="w-full border-warning-border bg-warning-surface text-warning hover:bg-warning-surface">{o.is_provisionally_reserved?'Included unassigned':'Include unassigned'}</Button></form></div>
  </div></div></Card>})}</div>}</section>
 </div>;
}