'use server';

import { revalidatePath } from 'next/cache';
import {
  importTrainerWorkbookV53,
} from './import';

export async function uploadTrainerTeachingWorkbookV53(
  formData: FormData,
) {
  const file = formData.get('workbook');

  if (!(file instanceof File) || file.size === 0) {
    throw new Error(
      'Select the completed trainer workbook.',
    );
  }

  if (!file.name.toLowerCase().endsWith('.xlsx')) {
    throw new Error(
      'Upload the Excel workbook generated by Academic Planner.',
    );
  }

  await importTrainerWorkbookV53(file);

  revalidatePath('/staff/teaching-documents');
  revalidatePath('/staff/units');
}
