import ExcelJS from 'exceljs';
import { createClient } from '@/lib/supabase/server';
import type {
  TrainerTeachingDocumentType,
} from './types';
import {
  loadAccessibleTrainerAllocationsV53,
} from './queries';

const WORKBOOK_VERSION = '5.3';

interface ManifestRow {
  documentType: TrainerTeachingDocumentType;
  ownerUserId: string;
  allocationId: string;
  unitId: string;
  unitCode: string;
  unitName: string;
  sheetName: string;
}

function normalize(value: unknown) {
  return String(value ?? '').trim();
}

function allowedDocumentType(
  value: string,
): value is TrainerTeachingDocumentType {
  return (
    value === 'course_outline' ||
    value === 'scheme_of_work'
  );
}

async function parseManifest(
  workbook: ExcelJS.Workbook,
) {
  const manifest = workbook.getWorksheet('_Manifest');

  if (!manifest) {
    throw new Error(
      'This is not a trainer workbook generated by Academic Planner.',
    );
  }

  const rows: ManifestRow[] = [];

  manifest.eachRow((row, rowNumber) => {
    if (rowNumber === 1) return;

    const version = normalize(row.getCell(1).value);
    const documentType = normalize(
      row.getCell(2).value,
    );
    const ownerUserId = normalize(
      row.getCell(3).value,
    );
    const allocationId = normalize(
      row.getCell(4).value,
    );
    const unitId = normalize(
      row.getCell(5).value,
    );
    const unitCode = normalize(
      row.getCell(6).value,
    );
    const unitName = normalize(
      row.getCell(7).value,
    );
    const sheetName = normalize(
      row.getCell(8).value,
    );

    if (!allocationId) return;

    if (version !== WORKBOOK_VERSION) {
      throw new Error(
        `Unsupported trainer workbook version ${version || 'unknown'}. Download a fresh workbook.`,
      );
    }

    if (!allowedDocumentType(documentType)) {
      throw new Error(
        'Trainer workbook document type is invalid.',
      );
    }

    rows.push({
      documentType,
      ownerUserId,
      allocationId,
      unitId,
      unitCode,
      unitName,
      sheetName,
    });
  });

  if (!rows.length) {
    throw new Error(
      'The trainer workbook contains no unit manifest records.',
    );
  }

  return rows;
}

function parseUnitSheet(
  workbook: ExcelJS.Workbook,
  row: ManifestRow,
) {
  const sheet = workbook.getWorksheet(row.sheetName);

  if (!sheet) {
    throw new Error(
      `Required unit sheet ${row.sheetName} is missing.`,
    );
  }

  // Identity comes from the hidden manifest, never from editable cells.
  const content: Record<string, string | number>[] = [];

  const headerRow = sheet.getRow(5);
  const headerMap = new Map<string, number>();

  headerRow.eachCell((cell, columnNumber) => {
    const header = normalize(cell.value);
    if (header) {
      headerMap.set(header, columnNumber);
    }
  });

  for (
    let rowNumber = 6;
    rowNumber <= sheet.rowCount;
    rowNumber += 1
  ) {
    const current = sheet.getRow(rowNumber);

    const topicColumn = headerMap.get('topic');
    if (!topicColumn) {
      throw new Error(
        `${row.sheetName}: topic column is missing.`,
      );
    }

    const topic = normalize(
      current.getCell(topicColumn).value,
    );

    if (!topic) continue;

    const get = (field: string) => {
      const column = headerMap.get(field);
      return column
        ? normalize(current.getCell(column).value)
        : '';
    };

    content.push({
      sequence:
        Number(get('sequence')) ||
        content.length + 1,
      topic,
      coverage: get('coverage'),
      learning_outcomes: get(
        'learning_outcomes',
      ),
      activities: get('activities'),
      assessment: get('assessment'),
      resources: get('resources'),
    });
  }

  return content;
}

export async function importTrainerWorkbookV53(
  file: File,
) {
  const supabase = await createClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    throw new Error('You must be signed in.');
  }

  const workbook = new ExcelJS.Workbook();

  try {
    await workbook.xlsx.load(
      Buffer.from(await file.arrayBuffer()) as never,
    );
  } catch {
    throw new Error(
      'The uploaded trainer workbook could not be read.',
    );
  }

  const manifest = await parseManifest(workbook);

  if (
    manifest.some(
      (row) => row.ownerUserId !== user.id,
    )
  ) {
    throw new Error(
      'This workbook belongs to another trainer account.',
    );
  }

  const accessible =
    await loadAccessibleTrainerAllocationsV53();

  const accessibleMap = new Map(
    accessible.map((row) => [
      row.allocationId,
      row,
    ]),
  );

  let imported = 0;
  let skippedEmpty = 0;

  for (const item of manifest) {
    const current =
      accessibleMap.get(item.allocationId);

    if (
      !current ||
      current.unitId !== item.unitId
    ) {
      throw new Error(
        `${item.unitCode}: allocation is no longer available to this trainer.`,
      );
    }

    const content = parseUnitSheet(
      workbook,
      item,
    );

    if (!content.length) {
      skippedEmpty += 1;
      continue;
    }

    const {
      data: currentVersion,
      error: currentError,
    } = await (supabase as any)
      .from('trainer_teaching_document_versions')
      .select('id,version_number')
      .eq('allocation_id', item.allocationId)
      .eq('document_type', item.documentType)
      .eq('status', 'active')
      .maybeSingle();

    if (currentError) {
      throw new Error(currentError.message);
    }

    // Missing-only workbooks should not normally encounter an active version.
    // If one appeared after download, skip it rather than accidentally replacing it.
    if (currentVersion) {
      continue;
    }

    const { error: insertError } = await (supabase as any)
      .from('trainer_teaching_document_versions')
      .insert({
        allocation_id: item.allocationId,
        unit_id: item.unitId,
        owner_user_id: user.id,
        document_type: item.documentType,
        version_number: 1,
        status: 'active',
        source_file_name: file.name,
        source_payload: {
          workbookVersion: WORKBOOK_VERSION,
          unitCode: item.unitCode,
          unitName: item.unitName,
          content,
        },
      });

    if (insertError) {
      throw new Error(insertError.message);
    }

    imported += 1;
  }

  return {
    imported,
    skippedEmpty,
  };
}
